
server:
  port: 8878
  servlet:
    context-path: /kuailexs
spring:
  application:
  name: invoice
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-interceptors: ConnectionState;StatementFinalizer;ResetAbandonedTimer;SlowQueryReport(threshold=2000)
    url: jdbc:mysql://127.0.0.1:3306/kuailexs?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    log-abandoned: true
    remove-abandoned: true
    bandon-when-percentage-full: 50
    suspect-timeout: 60
    remove-abandoned-timeout: 90
    type: com.alibaba.druid.pool.DruidDataSource

#  jackson:
#    default-property-inclusion: NON_NULL
mybatis:
#  type-aliases-package:com.neo.entity
  configuration:
    mapUnderscoreToCamelCase: true
